apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabi-deploy
  labels: 
    app: rabi-deploy
spec:
  replicas: 4
  selector:
    matchLabels: 
      app: rabi-deploy
  template:
    metadata:
      name: nginxserver
      labels:
        app: rabi-deploy
    spec:
      containers:
        - name: rabi-container
          image: nginx:latest